(function(){'use strict';
function request(action,type,key,payload,progress){var data=new FormData();data.append('op','editorial_library');data.append('action',action);data.append('csrf_token',window.csrfToken||'');data.append('item_type',type||'');data.append('item_key',key||'');if(payload)data.append('payload',JSON.stringify(payload));if(typeof progress==='number')data.append('progress',String(progress));return fetch('/ajax.php',{method:'POST',body:data,credentials:'same-origin',headers:{'X-Requested-With':'XMLHttpRequest'}}).then(function(r){return r.json().catch(function(){return{success:false};}).then(function(d){d.httpStatus=r.status;return d;});});}
function payload(button){return{title:button.getAttribute('data-library-title')||document.title,url:button.getAttribute('data-library-url')||window.location.pathname,image:button.getAttribute('data-library-image')||'',lang:(document.documentElement.lang||'vi').indexOf('zh')===0?'zh':((document.documentElement.lang||'vi').indexOf('en')===0?'en':'vn')};}
function setMatching(type,key,label){Array.prototype.forEach.call(document.querySelectorAll('[data-library-save]'),function(item){if(item.getAttribute('data-library-type')===type&&item.getAttribute('data-library-key')===key){item.classList.add('is-saved');item.textContent=label||item.getAttribute('data-saved-label')||'Saved';}});}
function hydrateSavedState(){var buttons=document.querySelectorAll('[data-library-save][data-library-type="saved"]');if(!buttons.length)return;fetch('/ajax.php?op=editorial_library&action=list&type=saved',{credentials:'same-origin',headers:{'X-Requested-With':'XMLHttpRequest'}}).then(function(r){if(!r.ok)return null;return r.json().catch(function(){return null;});}).then(function(d){if(!d||!d.success||!Array.isArray(d.items))return;d.items.forEach(function(item){setMatching('saved',String(item.item_key||''));});}).catch(function(){});}
document.addEventListener('click',function(e){var save=e.target.closest('[data-library-save]');if(save){e.preventDefault();if(save.disabled)return;save.disabled=true;var original=save.getAttribute('data-default-label')||save.textContent;request('save',save.getAttribute('data-library-type'),save.getAttribute('data-library-key'),payload(save),0).then(function(d){if(d.success){setMatching(save.getAttribute('data-library-type'),save.getAttribute('data-library-key'),save.getAttribute('data-saved-label'));return;}if(d.httpStatus===401){save.textContent=save.getAttribute('data-login-label')||'Sign in to save';setTimeout(function(){window.location.href='/dang-nhap?next='+encodeURIComponent(window.location.pathname+window.location.search);},700);return;}save.textContent=save.getAttribute('data-error-label')||'Try again';setTimeout(function(){save.textContent=original;},1800);}).catch(function(){save.textContent=save.getAttribute('data-error-label')||'Try again';}).finally(function(){save.disabled=false;});return;}var remove=e.target.closest('[data-library-remove]');if(remove){e.preventDefault();request('remove',remove.getAttribute('data-library-type'),remove.getAttribute('data-library-key')).then(function(d){if(d.success){var row=remove.closest('[data-library-row]');if(row)row.remove();}});}});
var article=document.querySelector('[data-reader-article][data-library-key]');if(article){var key=article.getAttribute('data-library-key'),last=-1,timer;function sync(){var max=Math.max(1,document.documentElement.scrollHeight-window.innerHeight);var progress=Math.max(0,Math.min(100,Math.round(window.scrollY/max*100)));if(progress===last)return;last=progress;request('save','history',key,{title:article.getAttribute('data-library-title')||document.title,url:window.location.pathname,image:article.getAttribute('data-library-image')||'',lang:(document.documentElement.lang||'vi').slice(0,2)},progress);}window.addEventListener('scroll',function(){clearTimeout(timer);timer=setTimeout(sync,1200);},{passive:true});sync();}
hydrateSavedState();
})();
